### PR TITLE
Bug fixes and new TREs

### PR DESCRIPTION
**Pull request by tclarke**
Putting pull request back in now that I'm up-to-date with master. There were a couple of comments in the previous request that I need to address still which I'm working now.

### CODE REVIEW

**Comment by JDanielSmith** [comment]
I'd *really* rather try to use **pybind11** to interface with Python; that keeps most code in C++ where the compiler can see it.

**Comment by tclarke** [comment]
We've got a fair amount of code written to the cython interface so it's unlikely I'll be able to build another wrapper so we'll probably just run off a fork. 
Can we get the remaining changes merged in? (If so I'll strip them out and update the pull request).

**Comment by JDanielSmith** [comment]
👍🏻

**Review by bradh — COMMENTED** [review]
Did you really want to commit that last file:
`nitro/nitro.xcodeproj/project.xcworkspace/xcuserdata/tclarke.xcuserdatad/UserInterfaceState.xcuserstate` ?

Not sure about the other XCode stuff either - not familiar with it, so could be noise. If so, my apologies.

**Comment by tclarke** [comment]
> Did you really want to commit that last file:
> `nitro/nitro.xcodeproj/project.xcworkspace/xcuserdata/tclarke.xcuserdatad/UserInterfaceState.xcuserstate` ?
> 
> Not sure about the other XCode stuff either - not familiar with it, so could be noise. If so, my apologies.

I don't see that in the final. I think it might have been added in one of the commits and removed later.

**Comment by bradh** [comment]
> I don't see that in the final. I think it might have been added in one of the commits and removed later.
Indeed. I though I was looking at the full list, but maybe got a filtered version somehow.

**Pull request merged**
