### PR TITLE
Workaround for msvc bug

### PR DESCRIPTION
**Pull request by JonathanMeans**
This only compiles when I configure with --disable-python

### CODE REVIEW

**Comment by asylvest** [comment]
Ugh, so it's not just a matter of how long the Select2DownSample_apply() function is?  If you instantiate the macro with a float type all by itself in a function, you still get the compiler error?  Stinks to have to repeat the whole function, but if that's the only thing we can do, fair enough.

**Comment by asylvest** [comment]
Bummer - Okie dokie

**Comment by scolcord** [comment]
Could you post a link or other reference to the MS bug report, so that we can tell when it's been fixed?

**Comment by JonathanMeans** [comment]
@scolcord https://developercommunity.visualstudio.com/content/problem/388506/compiler-crash-with-vs-2017-v1592.html

**Comment by scolcord** [comment]
Note better workaround in #111.

**Pull request merged**
